[package]
name = "flecs-wgpu-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "27.0.1"
winit = "0.30.12"
flecs_ecs = "0.2.1"
pollster = "0.4.0"
deref-derive = "0.1.0"
vello = { git = "https://github.com/linebender/vello.git", rev = "8f2f2564127812362d2c57ded20cad369e3a00fe" }
parley = { git = "https://github.com/linebender/parley.git", rev = "37a99ef6e30d387035a2d3afe5d31aeb0ddab637"}

[[example]]
name = "example"
